global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "prometheus.rules.yml"

scrape_configs:
  - job_name: "System and Container Resources"
    static_configs:
      - targets: ['192.168.44.44:9100', '192.168.44.44:8080']
        labels:
          environment: 'LOCAL'

  - job_name: 'Application URL Monitoring'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
          - https://192.168.44.44:9100
        labels:
          environment: 'LOCAL'
          service: "EXPORTER"

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.44.44:9115  # The blackbox exporter's real hostname:port.

