groups:
  - name: application_url_monitoring
    rules:
      - alert: ApplicationDown
        expr: probe_success == 0
        for: 10s
        labels:
          severity: "critical"
          group: application_url_monitoring
        annotations:
          summary: "Service {{$labels.service}} endpoint {{ $labels.instance }} down"
          description: "{{$labels.instance}} has been down for more than 10 seconds."

  - name: resources_monitoring
    rules:
      - alert: InstanceDown
        expr: up{ job=~".*Resources" } == 0
        for: 1m
        labels:
          severity: page
          group: resources_monitoring
        annotations:
          summary: "\nHost {{ $labels.nodename }} is down\n"
          description: "{{$labels.instance}} has been down for more than 1 minute."
      
      - alert: HostOutOfMemory
        expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100) * on(instance) group_left(nodename) node_uname_info < 10
        for: 30s
        labels:
          severity: warning
          group: resources_monitoring
        annotations:
          summary: "Host: {{ $labels.nodename }}\nNode memory is filling up (< 10% left) VALUE = {{ $value | printf \"%.2f\" }}%\n"
          description: "Node memory is filling up (< 10% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
      
      - alert: HostOutOfDiskSpace
        expr: ((node_filesystem_avail_bytes{mountpoint="/"} * 100) / node_filesystem_size_bytes{mountpoint="/"}) * on(instance) group_left(nodename) node_uname_info < 20
        for: 30s
        labels:
          severity: warning
          group: resources_monitoring
        annotations:
          summary: "Host: {{ $labels.nodename }}\nDisk is almost full (< 20% left) VALUE = {{ $value | printf \"%.2f\" }}%\n"
          description: "Disk is almost full (< 20% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

      - alert: HostHighCpuLoad
        expr: (100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) * on(instance) group_left(nodename) node_uname_info > 90
        for: 2m
        labels:
          severity: warning
          group: resources_monitoring
        annotations:
          summary: "Host: {{ $labels.nodename }}\nCPU load is > 80% VALUE = {{ $value | printf \"%.2f\" }}%\n"
          description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
      